#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
  printf -- 'Do not run as root\n'
  exit 1
fi

# Do not exec here since bww will exec for you
# Indicator kdeconnect must see that kdeconnectd is running
"${HOME}/bin/bww" --bind-if-exists "${HOME}/downloads" --forcename="kdeconnectd" /usr/lib/kdeconnectd-real "$@"
