#!/bin/sh

if [ "$(id -u)" -eq 0 ]; then
  printf -- "Do not run as root\\n"
  exit 1
fi

if [ ! -e "${HOME}/bin/bww" ] || [ ! -x "${HOME}/bin/bww" ]; then
  printf -- 'kdeconnectd is missing bww script in %s' "${HOME}/bin" >> "${HOME}/kdeconnectd_error.log"
  exit 1
fi

exec "${HOME}/bin/bww" /usr/lib/kdeconnectd-real "$@"
